In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import numpy as np


from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

import time
import pandas as pd
import numpy as np


# Criar o navegador
driver = webdriver.Chrome()

# Criar o WebDriverWait
wait = WebDriverWait(driver, 10)


HOST = os.getenv("MYSQL_HOST")
USER = os.getenv("MYSQL_USER")
PASSWORD = os.getenv("MYSQL_PASSWORD")
DATABASE = os.getenv("MYSQL_DATABASE")
# print(PASSWORD)

In [ ]:
from sqlalchemy import create_engine
import pandas as pd
import time

engine = create_engine(
    f"mysql+pymysql://root:{PASSWORD}@localhost:3306/FIPE"
)

query = f"""
SELECT * FROM tabela_fipe limit 1
"""
df = pd.read_sql(query, con=engine)
df

   Marca          Modelo            Ano
0  Acura  Legend 3.2/3.5  1998 Gasolina

In [ ]:
for _, linha in df.iterrows():

    marca = linha["Marca"]
    modelo = linha["Modelo"]
    ano = linha["Ano"]

print(f"Marca: {marca}, Modelo: {modelo}, Ano: {ano}")

Marca: Acura, Modelo: Legend 3.2/3.5, Ano: 1998 Gasolina

In [17]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time


# ============================================================
# INICIAR SELENIUM
# ============================================================
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 20)
driver.get("https://veiculos.fipe.org.br/")
driver.maximize_window()
time.sleep(3)

# ============================================================
# 1. ABRIR "CONSULTA DE CARROS E UTILITÁRIOS PEQUENOS"
# ============================================================

titulo = wait.until(
    EC.presence_of_element_located(
        (
            By.XPATH,
            "//div[contains(@class,'title') and "
            "normalize-space()='Consulta de Carros e Utilitários Pequenos']"
        )
    )
)

# Leva o elemento para uma posição visível
driver.execute_script(
    "arguments[0].scrollIntoView({block: 'center'});",
    titulo
)

time.sleep(0.5)

# Clique via JavaScript para evitar problemas de overlay
driver.execute_script(
    "arguments[0].click();",
    titulo
)

time.sleep(2)

In [18]:

# ============================================================
# FUNÇÃO PARA SELECIONAR CARRO
# ============================================================

def selecionar_carro(marca, modelo, ano):

    # ========================================================
    # MARCA
    # ========================================================

    campo = wait.until(
        EC.element_to_be_clickable(
            (
                By.XPATH,
                "//select[@id='selectMarcacarro']"
                "/following-sibling::div[contains(@class,'chosen-container')]"
            )
        )
    )

    campo.click()

    time.sleep(0.5)

    opcoes = wait.until(
        EC.presence_of_all_elements_located(
            (
                By.CSS_SELECTOR,
                "li.active-result"
            )
        )
    )

    for opcao in opcoes:

        if opcao.text.strip() == marca:

            opcao.click()

            break

    else:

        raise Exception(
            f"Marca não encontrada: {marca}"
        )


    # ========================================================
    # MODELO
    # ========================================================

    campo = wait.until(
        EC.element_to_be_clickable(
            (
                By.XPATH,
                "//select[@id='selectAnoModelocarro']"
                "/following-sibling::div[contains(@class,'chosen-container')]"
            )
        )
    )

    campo.click()

    time.sleep(0.5)

    opcoes = wait.until(
        EC.presence_of_all_elements_located(
            (
                By.CSS_SELECTOR,
                "li.active-result"
            )
        )
    )

    for opcao in opcoes:

        if opcao.text.strip() == modelo:

            opcao.click()

            break

    else:

        raise Exception(
            f"Modelo não encontrado: {modelo}"
        )


    # ========================================================
    # ANO
    # ========================================================

    campo = wait.until(
        EC.element_to_be_clickable(
            (
                By.XPATH,
                "//select[@id='selectAnocarro']"
                "/following-sibling::div[contains(@class,'chosen-container')]"
            )
        )
    )

    campo.click()

    time.sleep(0.5)

    opcoes = wait.until(
        EC.presence_of_all_elements_located(
            (
                By.CSS_SELECTOR,
                "li.active-result"
            )
        )
    )

    for opcao in opcoes:

        if opcao.text.strip() == ano:

            opcao.click()

            break

    else:

        raise Exception(
            f"Ano não encontrado: {ano}"
        )


    # ========================================================
    # RESULTADO
    # ========================================================

    print("Marca :", marca)
    print("Modelo:", modelo)
    print("Ano   :", ano)
    
for _, linha in df.iterrows():

    marca = linha["Marca"]
    modelo = linha["Modelo"]
    ano = linha["Ano"]

    selecionar_carro(
        marca,
        modelo,
        ano
    )

Marca : Acura
Modelo: Legend 3.2/3.5
Ano   : 1998 Gasolina

In [19]:
botao = wait.until(
    EC.element_to_be_clickable(
        (By.XPATH, "//a[normalize-space()='Pesquisar']")
    )
)

botao.click()

In [20]:
def extrair_fipe():

    tabela = wait.until(
        EC.presence_of_element_located(
            (By.XPATH, "//tbody[.//td[contains(., 'Preço Médio')]]")
        )
    )

    dados = {}

    for linha in tabela.find_elements(By.TAG_NAME, "tr"):
        colunas = linha.find_elements(By.TAG_NAME, "td")

        if len(colunas) == 2:
            campo = colunas[0].text.strip().replace(":", "")
            valor = colunas[1].text.strip()

            dados[campo] = valor

    return dados

dados = extrair_fipe()
df = pd.DataFrame([dados])
df

,Mês de referência,Código Fipe,Marca,Modelo,Ano Modelo,Autenticação,Data da consulta,Preço Médio
0,agosto de 2026,038002-4,Acura,Legend 3.2/3.5,1998 Gasolina,mnkh76bpng,"domingo, 9 de agosto de 2026 15:58","R$ 24.668,00"